#!/usr/bin/env bash
#This script counts from 1 to 100. Multiples of 3 = Fizz, multiples of 5 = Buzz, multiples of both = FizzBuzz
for ((i=1; i<=100; i++))
do
	if ! ((i%15)); then
		echo "FizzBuzz"
	elif ! ((i%3)); then
		echo "Fizz"
	elif ! ((i%5)); then
		echo "Buzz"
	else
		echo $i
	fi
done
