#!/usr/bin/env bash
#This script is displaying "bad luck" on line 4 and "good luck" on line 8 instead of "Best School"
n=0
while [ $n -lt 10 ]
do
	((n++))
	if [ $n == 4 ]
	then
		echo "bad luck"
		continue
	elif [ $n == 8 ]
	then
		echo "good luck"
		continue
	else
		echo "Best School" $n | cut -d" " -f-2
	fi
	
done
