#!/usr/bin/env bash
#This script is printing out 0 to 12 hours and 1 to 59 minutes on a clock
h=-1
m=0
while [ $h -lt 12 ]
do
	h=$((h+1))
	echo Hour: $h
	while [ $m -lt 59 ]
	do
		m=$((m+1))
		echo $m
	done
	m=0
done
