#!/usr/bin/env bash
#Testing if/then/else for file school
if [ -e ./school ]
then
	echo "school file exists"
else
	echo "school file does not exist"
fi
while [ -e ./school ] 
do
if [ -s ./school ]
then
	echo "school file is not empty"
	break
else
	echo "school file is empty"
	break
fi
done
if [ -f ./school ]
then
	echo "school is a regular file"
fi
